# Generated by Django 6.0.4 on 2026-05-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateField(),
        ),
    ]
